version: '3.4'

services:
  openzipkin:
    image: openzipkin/zipkin
    container_name: openzipkin
    hostname: openzipkin
    restart: unless-stopped
    ports:
      - 9411:9411
    networks:
      - trace-net

networks:
  trace-net:
    name: trace-net
    driver: bridge
